service:
  type: "Lobby" # Vanilla or Lobby
  
server:
  name: "서버이름"  # 각 서버마다 다른 이름 설정

database:
  host: "localhost"
  port: 3306
  name: "database_name"
  user: "username"
  password: "password"

# HMCCosmetics 옷장 위치 시스템 설정
wardrobe:
  world: "world"  # 옷장이 위치한 월드 이름
  location:
    x: 31.494
    y: 64.0
    z: 78.7
  radius: 2.0  # 옷장 활성화 반경 (블록 단위)

debug:
  farmitemrestriction: true
  landprotection: true
  farmvillage: true
  myland: true
  chestprotection: true
  farmcropprotection: true

# 책 시스템 설정
book_system:
  # 웹서버 활성화 여부
  enable_web_server: true
  
  # 웹서버 주소 및 포트
  # nginx proxy 사용 시: "127.0.0.1" (내부에서만 접속)
  # 직접 외부 접속 시: "0.0.0.0" (외부에서 직접 접속 가능)
  web_host: "0.0.0.0"
  web_port: 9090
  
  # 외부 접속 도메인 설정 (nginx proxy 사용 시)
  external_domain: "book.mine.lukehemmin.com"
  external_protocol: "https"  # http 또는 https
  
  # CORS 설정
  enable_cors: true
  allowed_origins:
    - "https://book.mine.lukehemmin.com"
    - "http://localhost:9090"  # 개발용
  
  # 세션 설정
  session_expiry_hours: 24          # 웹 세션 만료 시간 (시간)
  auth_code_expiry_minutes: 5       # 인증 코드 만료 시간 (분)
  max_sessions_per_player: 3        # 플레이어당 최대 세션 수
  
  # 시즌 설정
  current_season: "Season1"         # 현재 시즌 (책 저장 시 태그로 사용)
  
  # 로깅 설정
  log_book_reads: false             # 책 읽기 로그 활성화