name: LukeVanilla
version: '1.0-SNAPSHOT'
main: com.lukehemmin.lukeVanilla.Main
api-version: '1.21.3'
author: LukeHemmin
website: https://github.com/lukehemmin/LukeVanilla

commands:
  nametag:
    description: "플레이어 칭호를 변경할 수 있습니다."
    usage: "/nametag <nickname> <nametag>"
    permission: "lukevanilla.nametag"
    permission-message: "You do not have permission to use this command."
  delnametag:
    description: "플레이어의 칭호를 제거합니다."
    usage: "/delnametag <nickname>"
    permission: "lukevanilla.nametag"
    permission-message: "You do not have permission to use this command."
  item:
    description: "Manage item names and descriptions."
    usage: "/item <setname|adddesc|removedesc|cleardesc|info>"
    permission: "lukevanilla.item"
    permission-message: "You do not have permission to use this command."
  infomessage:
    permission: "lukevanilla.admin"
    permission-message: "You do not have permission to use this command."
  wleh:
    description: "지도 사이트 링크를 표시하는 명령어 입니다."
    usage: "/wleh 또는 /지도"
  지도:
    description: "지도 사이트 링크를 표시하는 명령어 입니다."
    usage: "/wleh 또는 /지도"
  할로윈:
    description: "할로윈 아이템 소유 명령어"
    usage: "/할로윈 아이템 소유"
  티토커메시지:
    description: "티토커 채팅 메시지를 활성화/비활성화합니다."
    usage: "/티토커메시지 <보기|끄기>"
  투명액자:
    description: "투명 액자를 받습니다"
    usage: "/투명액자"
    permission: "lukevanilla.transparentframe"

permissions:
  lukevanilla.nametag:
    description: "Allows the use of the /nametag command"
    default: op
  lukevanilla.item:
    description: "Allows the use of the /item command"
    default: op
  lukevanilla.admin:
    description: "Allows the use of all commands"
    default: op
  lukevanilla.transparentframe:
    description: "투명 액자 명령어 사용 권한"
    default: op