name: LukeVanilla
version: '1.0-SNAPSHOT'
main: com.lukehemmin.lukeVanilla.Main
api-version: '1.21'

commands:
  nametag:
    description: "플레이어 칭호를 변경할 수 있습니다."
    usage: "/nametag <nickname> <nametag>"
    permission: "lukevanilla.nametag"
    permission-message: "You do not have permission to use this command."
  item:
    description: "Manage item names and descriptions."
    usage: "/item <setname|adddesc|removedesc|cleardesc|info>"
    permission: "lukevanilla.item"
    permission-message: "You do not have permission to use this command."

permissions:
  lukevanilla.nametag:
    description: "Allows the use of the /nametag command"
    default: op
  lukevanilla.item:
    description: "Allows the use of the /item command"
    default: op