name: LukeVanilla
version: '1.0-SNAPSHOT'
main: com.lukehemmin.lukeVanilla.Main
api-version: '1.21.4'
author: LukeHemmin
website: https://github.com/lukehemmin/LukeVanilla
#depend:
softdepend:
  - Oraxen
  - Citizens

commands:
  nametag:
    description: "플레이어 칭호를 변경할 수 있습니다."
    usage: "/nametag <nickname> <nametag>"
    permission: "lukevanilla.nametag"
    permission-message: "You do not have permission to use this command."
  delnametag:
    description: "플레이어의 칭호를 제거합니다."
    usage: "/delnametag <nickname>"
    permission: "lukevanilla.nametag"
    permission-message: "You do not have permission to use this command."
  item:
    description: "Manage item names and descriptions."
    usage: "/item <setname|adddesc|removedesc|cleardesc|info>"
    permission: "lukevanilla.item"
    permission-message: "You do not have permission to use this command."
  아이템:
    description: "이벤트 아이템을 등록하거나 조회하고 수령합니다."
    usage: "/아이템 [등록|조회|수령] [이벤트타입]"
  infomessage:
    permission: "lukevanilla.admin"
    permission-message: "You do not have permission to use this command."
  wleh:
    description: "지도 사이트 링크를 표시하는 명령어 입니다."
    usage: "/wleh 또는 /지도"
  지도:
    description: "지도 사이트 링크를 표시하는 명령어 입니다."
    usage: "/wleh 또는 /지도"
  할로윈:
    description: "할로윈 아이템 명령어"
    usage: "/할로윈 아이템"
  티토커메시지:
    description: "티토커 채팅 메시지를 활성화/비활성화합니다."
    usage: "/티토커메시지 <보기|끄기>"
  투명액자:
    description: "투명 액자를 받습니다"
    usage: "/투명액자"
    permission: "lukevanilla.transparentframe"
  opennextseasongui:
    description: "다음 시즌에 가져갈 아이템을 넣을 GUI를 엽니다."
    usage: "/opennextseasongui"
  pl:
  plugins:
  lukeplugininfo:
  돈:
    description: 돈 관련 명령어
    usage: /돈 [보내기 <플레이어> <금액>|도움말]
    aliases: [ money ]
  ehs:
    description: 돈 관련 명령어
    usage: /ehs [보내기 <플레이어> <금액>|도움말]
    aliases: [ 돈 ]
  refreshmessages:
    description: 접속 및 퇴장 메시지를 갱신합니다.
    usage: /refreshmessages
    permission: lukevanilla.refreshmessages
  lukereload:
    description: 플러그인을 재시작합니다.
    usage: /lukereload
    permission: lukevanilla.reload
    permission-message: 이 명령어를 사용할 권한이 없습니다.
  아이템복구:
    description: 커스텀 아이템을 복구합니다.
    usage: /아이템복구
  관리자채팅:
    description: "관리자 전용 채팅을 활성화/비활성화합니다."
    usage: "/관리자채팅 <활성화|비활성화>"
    permission: "lukevanilla.adminchat"
    permission-message: "이 명령어를 사용할 권한이 없습니다."
  craftallow:
    description: "커스텀 아이템을 제작대에 5분 동안 넣을 수 있도록 합니다."
    usage: /craftallow
  발렌타인방패받기:
    description: 발렌타인 기념 방패를 받습니다.
    usage: /발렌타인방패받기
  아이템정보:
    description: "현재 들고 있는 아이템의 통계 정보를 조회합니다."
    usage: "/아이템정보"
    aliases: [ itemstats ]
  itemstats:
    description: "아이템 통계 시스템 관리 명령어"
    usage: "/itemstats log <on|off>"
    permission: "itemstats.admin"
    permission-message: "이 명령어를 사용할 권한이 없습니다."
  sit:
    description: "현재 위치에 앉습니다."
    usage: "/sit"
  lay:
    description: "현재 위치에 눕습니다."
    usage: "/lay"
  crawl:
    description: "기어다니기 모드를 활성화/비활성화합니다."
    usage: "/crawl"

permissions:
  lukevanilla.nametag:
    description: "Allows the use of the /nametag command"
    default: op
  lukevanilla.item:
    description: "Allows the use of the /item command"
    default: op
  lukevanilla.admin:
    description: "Allows the use of all commands"
    default: op
  lukevanilla.transparentframe:
    description: "투명 액자 명령어 사용 권한"
    default: op
  bukkit.command.plugins:
    default: false
  bukkit.command.pl:
    default: false
  lukevanilla.shop:
    description: 상점 명령어를 사용할 수 있는 권한
    default: op
  lukevanilla.refreshmessages:
    description: "접속 및 퇴장 메시지를 갱신할 수 있는 권한"
    default: op
  lukevanilla.reload:
    description: "플러그인을 재시작할 수 있는 권한"
    default: op
  lukevanilla.adminchat:
    description: "관리자 채팅 사용 권한"
    default: op
  itemstats.admin:
    description: "아이템 통계 시스템 관리 명령어 사용 권한"
    default: op