# .github/workflows/build.yml

name: Build Project

on:
  push:
    branches: ['develop', 'main']
  pull_request:
    branches: ['develop', 'main']

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PLUGIN_DESTINATION: "./build/libs"  # CI 환경에서 사용할 상대 경로 설정

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      # gradlew 스크립트에 실행 권한 부여
      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle (ShadowJar)
        run: ./gradlew shadowJar

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build/libs/
